<template>
  <section class="content" id="cases">
    <div class="line-bg">
      <img src="~/static/images/line-bg.svg" alt="" />
    </div>
    <h3 class="title">Nydus Use Cases</h3>
    <div class="desc">
      <span><span class="bold">Not Just Focus on</span> Data Distribution</span>
    </div>
    <div class="cases">
      <div class="item">
        <div class="icon color-1">
          <img src="~/static/images/case-image.svg" alt="" class="emoji" />
        </div>
        <div class="intro">
          <div class="title">Container Image</div>
          <div class="desc">
            Compared to OCI image, Nydus image pull times are reduced from
            minutes to seconds, in combination with Dragonfly P2P distribution,
            Nydus helps large-scale clusters save network bandwidth and reduce
            network load.
          </div>
        </div>
      </div>
      <div class="item">
        <div class="icon color-2">
          <img src="~/static/images/case-func.svg" alt="" class="emoji" />
        </div>
        <div class="intro">
          <div class="title">Function Computing</div>
          <div class="desc">
            Reduces package download and decompression time, improves startup
            speed under high concurrency, supports high creation frequency and
            high deployment density, and reduces CPU and memory load. See
            <a
              target="_blank"
              class="inline-highlight"
              href="https://developer.aliyun.com/article/799903"
            >
              usecase
            </a>
            .
          </div>
        </div>
      </div>
      <div class="item">
        <div class="icon color-3">
          <img src="~/static/images/case-risk.svg" alt="" class="emoji" />
        </div>
        <div class="intro">
          <div class="title">Vulnerability Scanning</div>
          <div class="desc">
            Do a security scan of the image based on a list of known risks,
            thanks to the Nydus on-demand loading feature, which greatly
            increases the speed of scanning risky data, code, and packages.
          </div>
        </div>
      </div>
      <div class="item">
        <div class="icon color-4">
          <img src="~/static/images/case-package.svg" alt="" class="emoji" />
        </div>
        <div class="intro">
          <div class="title">Dependency Management</div>
          <div class="desc">
            Use Nydus to increase the speed of dependency installation by
            reducing the network and IO load of the large number of small files
            generated by dependency package decompression. See
            <a
              target="_blank"
              class="inline-highlight"
              href="https://dev.to/atian25/in-depth-of-tnpm-rapid-mode-how-could-we-fast-10s-than-pnpm-3bpp"
            >
              usecase
            </a>
            .
          </div>
        </div>
      </div>
      <div class="item">
        <div class="icon color-5">
          <img src="~/static/images/case-insight.svg" alt="" class="emoji" />
        </div>
        <div class="intro">
          <div class="title">Data Insight</div>
          <div class="desc">
            The implementation of Nydus at the file system level, can analyze
            the usage in image, file, and data chunk for business, achieve
            global data de-duplication, reduce the size of image layer for
            high-frequency incremental builds.
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: "Case",
};
</script>

<style lang="less" scoped>
@import "@/static/css/base";

.content {
  margin-bottom: 60px;
  padding-top: 250px;
  .line-bg {
    top: 100px;
    transform: scaleY(-1) scaleX(-1);
  }
  > .title {
    font-size: 26px;
    position: relative;
    width: fit-content;
    margin: 0 auto;
    &::after {
      content: "";
      border: 4px solid @color-main;
      position: absolute;
      width: 55px;
      left: 50%;
      margin-left: -27px;
      top: -30px;
      z-index: -1;
    }
    &::before {
      content: "";
      width: 45px;
      height: 45px;
      border-radius: 50%;
      background-color: @color-tone;
      position: absolute;
      z-index: -1;
      left: -20px;
      top: -10px;
    }
    .highlight {
      color: @color-highlight;
    }
  }
  > .desc {
    margin: 0 auto;
    width: fit-content;
    margin-top: 15px;
    color: @color-highlight;
    font-weight: 400;
    font-size: 22px;
    display: flex;
    align-items: center;
    @media @tablet {
      flex-direction: column;
      text-align: center;
      font-size: 18px;
    }
    .bold {
      font-weight: 600;
    }
  }
  .cases {
    border-radius: 20px;
    display: flex;
    flex-wrap: wrap;
    margin-top: 50px;
    justify-content: space-between;
    .item {
      display: flex;
      align-items: center;
      margin-bottom: 40px;
      @media @tablet {
        flex-direction: column;
      }
      &:last-child {
        margin-bottom: 0;
      }
      .icon {
        &.color-1 {
          background-color: #55e2d6;
        }
        &.color-2 {
          background-color: #9eff96;
        }
        &.color-3 {
          background-color: #a1d0ff;
        }
        &.color-4 {
          background-color: #ffafaf;
        }
        &.color-5 {
          background-color: #ffafec;
        }
        width: 75px;
        height: 75px;
        border-radius: 50%;
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        img {
          width: 35px;
        }
      }
      .intro {
        margin-left: 30px;
        @media @tablet {
          margin-left: 0;
          margin-top: 20px;
        }
        .title {
          font-size: 20px;
          font-weight: 600;
        }
        .desc {
          font-size: 16px;
          width: 480px;
          @media @tablet {
            width: 100%;
          }
        }
      }
    }
  }
}
</style>
